### ISSUE TITLE
Validation of submitted solutions

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/codegolf#13]

**Comment by Jaykul** [comment]
:+1:   Need pester tests for expected output :grinning:

**Comment by adamdriscoll** [comment]
@Jaykul  That's a good idea. Think I should do that instead of comparing the expected output to the actual output?

**Comment by adamdriscoll** [comment]
Hmm Azure Functions don't support Pester or Install-Module. Will need to do more research.

**Comment by Jaykul** [comment]
Yeah, currently there's a whole category of interesting problems things that can't be done well because the output is rich, like http://www.code-golf.com/problem/view/ConvertTo-DataTable

Testing that project by just comparing string output would turn the _problem_ into a single call to `Format-Table` ...

**Comment by Jaykul** [comment]
Darn. I guess maybe you could just put in something like [Must](https://github.com/PoshCode/PSGit/blob/dev/Tests/Must.Steps.ps1) (or `should`, but that's much messier to include) and let people _write code_ in the "expected" -- then you could assume that if it doesn't throw, it passes?

**Comment by adamdriscoll** [comment]
Got it installed! You can use the Kudu ZIP API to upload and expand ZIPs to the web app running the functions to make stuff like this available! 

![image](https://cloud.githubusercontent.com/assets/1256531/18919363/6be2eb22-8563-11e6-9fc0-8ba04ba9f4e0.png)

**Comment by adamdriscoll** [comment]
Works now!
