### ISSUE TITLE
Input and Output clarity

### ISSUE THREAD

**Issue by KirkMunro** [adamdriscoll/codegolf#25]
Some answers are taking the Input sample as the one and only input, which makes for some responses that are shortest that work for that and only that input. e.g. 8+4+0+0+1, or $a[-1,-3]. You should clarify that the input is sample/example input, and that the only thing that will be constant regardless of the input is the variable name so that hardcoded responses can be ignored.

Similarly, for Output it would be better to identify if the intent is exact output or output containing at least what is shown, because the two result in wildly different results (e.g. ps).

**Comment by adamdriscoll** [comment]
That's a great point, Kirk. I hope that voting would take car or some of that stuff. Since hardcoding the solution really does bypass the whole concept, users could take it in their own hands to moderate some of that. 

I was going to enforce that code is passing for a particular output, but as you say some problems output may just be examples.

**Comment by adamdriscoll** [comment]
Now you can supply multiple input\output combinations so this should be fixed!
